[XTrain,TTrain] = japaneseVowelsTrainData;
[XTest,TTest] = japaneseVowelsTestData;

inputSize = 12;
numHiddenUnits = 100;
numClasses = 9;
maxEpochs = 40;
miniBatchSize = 27;

% ActivationFunctions = ["tanh_mex", "tanh_mex", "sigmoid_mex", "sigmoid_mex", "sigmoid_mex"];
% ActivationParameters = [0, 0, 0, 0 ,0];

k_param = @(a, b) 1 + exp(a .* b);
ActivationFunctions = ["zorro_tanh_mex", "zorro_tanh_mex", "zorro_sigm_mex", "zorro_sigm_mex", "zorro_sigm_mex"];
ActivationParameters = [...
    [1, 4, k_param(4, 2)], ...
    [1, 4, k_param(4, 2)], ...
    [0.5, 4, k_param(4, 2)], ...
    [0.5, 4, k_param(4, 2)], ...
    [0.5, 4, k_param(4, 2)]];

layers = [ ...
   sequenceInputLayer(inputSize),
   zbilstmLayer(numHiddenUnits, ...
        'OutputMode', 'last', ... % set in order: A, Z, I, F, O
        'ActivationFunctions', ActivationFunctions, ...
        'ActivationParameters', ActivationParameters, ...
        'GeneralStrategy', 'ZBiLSTMStrategySimple')
   fullyConnectedLayer(numClasses)
   softmaxLayer
   classificationLayer];

options = trainingOptions('adam', ...
    'ExecutionEnvironment','cpu', ...
    'GradientThreshold',1, ...
    'MaxEpochs',maxEpochs, ...
    'MiniBatchSize',miniBatchSize, ...
    'SequenceLength','longest', ...
    'Shuffle','never', ...
    'Verbose',0, ...
    'Plots','training-progress', ...
    'LearnRateSchedule','piecewise', ... %none
    'LearnRateDropPeriod',30, ... %none
    'LearnRateDropFactor',0.2, ... %none
    'ValidationData', {XTest, TTest}, ... 
    'ValidationFrequency',50, ...
    'ValidationPatience',Inf ...
);

%options = trainingOptions("adam",MiniBatchSize=1,SequencePaddingDirection="left");
t_init = tic();
[net, info] = trainNetwork(XTrain,TTrain,layers,options);
t_diff = toc(t_init);
disp(['Training time: ' num2str(t_diff) ' sec.'])

YTest = classify(net,XTest,MiniBatchSize=27,Acceleration="none");
accuracy = mean(YTest==TTest)

%save('japaneseVowels_net', "net")
%save('japaneseVowels_info', "info")